<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>BlazorUniversityCom</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Statiq.Web" Version="1.0.0-beta.60" />
    <PackageReference Include="Statiq.Docs" Version="1.0.0-beta.17" />
    <PackageReference Include="Statiq.Lunr" Version="1.0.0-beta.72" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\blazor-university-tailwind\blazor-university-tailwind.csproj" />
  </ItemGroup>
</Project>
